name: Update IPTV List
on:
  schedule:
    - cron: '0 0 * * *' # Chạy tự động lúc 00:00 mỗi ngày
  workflow_dispatch: # Nút bấm để chạy tay khi cần

jobs:
  filter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Lay va loc file
        run: |
          # 1. Tải file gốc về máy chủ GitHub
          curl -L "https://byvn.net/hxcv-iptv" > raw.m3u
          
          # 2. Tạo file mới với tiêu đề chuẩn
          echo "#EXTM3U" > hfb_list.m3u
          
          # 3. Lọc kênh: Tìm dòng chứa từ khóa, lấy thêm 1 dòng địa chỉ phía dưới (-A 1)
          # Bạn muốn thêm kênh nào thì viết thêm vào giữa các dấu gạch đứng |
          grep -E "VTV|VTC|Bóng đá|Sport|Cartoon|HBO" -A 1 raw.m3u >> hfb_list.m3u
          
      - name: Day file len lai GitHub
        run: |
          git config --global user.name 'Bot-Minh-Chau'
          git config --global user.email 'bot@github.com'
          git add hfb_list.m3u
          git commit -m "Bot da loc xong kenh moi" || exit 0
          git push
