name: Update IPTV List
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  filter:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Run
        run: |
          # 1. Tải file gốc
          curl -L "https://raw.githubusercontent.com/minhtan001/IPTV-Auto/refs/heads/playlists/all.m3u" > raw.m3u
          
          # 2. Tạo file trắng để TV không bị đứng máy
          echo "#EXTM3U" > hfb_list.m3u
          
          # 3. Lọc từ khóa "vs" (Thêm || true để không bao giờ báo lỗi đỏ nữa)
          # Lệnh này sẽ tìm chữ "vs" không phân biệt hoa thường
          grep -Ei "vs" -A 1 raw.m3u >> hfb_list.m3u || true
          
          # 4. Lưu lại vào kho của bạn
          git config --global user.name 'bot'
          git config --global user.email 'bot@github.com'
          git add hfb_list.m3u
          git commit -m "update" || exit 0
          git push
